puede hacer los cambios=)
Fran34Arci/segundocuatrimestre pull request #2
Opened 2024-10-04 18:52 UTC by Fran34Arci

ahí encontré el error, me faltaban las comillas ```

getDatos() {
    return(
     `Marca: ${this.getMarca()}
      Modelo: ${this.getModelo()} 
      Patente: ${ this.getPatente()}
      Annio: ${this.getAnnio()}
      Auto: ${this.getAuto()}
      Camion: ${this.getCamion()}
      Moto: ${this.getMoto()}`
    )
    
}

2024-10-04 19:09 UTC, SofiZ2001 requested changes
Un comment fran

2024-10-04 19:09 UTC, SofiZ2001 commented on ejercicioautomt/auto.ts
>      getnumpuertas(): number {
Agregate modificador de acceso a todas las funciones de todas las clases

2024-10-07 22:23 UTC, Fran34Arci reviewed
modificadores 1

2024-10-08 13:07 UTC, SofiZ2001 approved these changes
LG2M

2024-10-08 13:13 UTC, merged