entrega trabajo practico juego rpg
Fran34Arci/segundocuatrimestre pull request #7
Opened 2024-10-22 00:59 UTC by Fran34Arci

2024-10-23 17:38 UTC, SofiZ2001 requested changes
2 mini comments!

2024-10-23 17:38 UTC, SofiZ2001 commented on juegorpg/personaje.ts
> +}
Si no va a ser implementado en el padre y solo en los hijos, no debería ser una funcion abstracta?

2024-10-23 17:38 UTC, SofiZ2001 commented on juegorpg/main.ts
> +}
Te está faltando la parte del ejercicio donde tengas algun personaje evolucionado. Ej teniendo la clase Arquero, podrias tener un ArqueroMejorado

2024-10-23 23:17 UTC, Fran34Arci commented on juegorpg/personaje.ts
> +}
Lo había planteado mas como sobrecarga de métodos, pero ahora que veo el machete me falto ponerle un ..."trow new error".. . para que no quede vacía y lo veo relacionado a las buenas practicas, ya que la función vacía no causa errores y funciona igual.
Entonces... debo declarar la clase personaje como abstracta, ya que no la uso directamente si no que la uso solo para que hereden los atributos y funciones a las demás clases, de esta forma puedo declarar abstractas las funciones y como la función atacar esta vacía y no la uso directamente con los demás personajes como la función esquivar o defender, la declaro de esta forma  ..." abstract atacar():void; "... . te lo planteo así para saber si entendí por que abstracta la función y no solo usar la herencia...

2024-10-23 23:20 UTC, Fran34Arci commented on juegorpg/main.ts
> +}
Esa parte esta, es cuando sube de nivel y pasa a ser Arquero nivel 2 y desbloquea las flechas de plata y en nivel 3 las flechas de oro...o? no especificaba como hacerlo. como sugerís que sea ? o lo implemente ?

2024-10-23 23:59 UTC, SofiZ2001 commented on juegorpg/main.ts
> +}
La idea es tener una clase ArqueroMejorado, que sea como una mejoría de la clase Arquero, ahi tendrias que usar herencia. Por ahi esa parte fue medio confusa

2024-10-24 00:02 UTC, SofiZ2001 commented on juegorpg/personaje.ts
> +}
Mmm no entendi mucho como lo habias planteado, pero en si una funcion que se implementa, y esta vacía no se usa. Si no se usa no tiene sentido que exista.
Peeero si la usan los hijos! Solamente que no tiene sentido que lo implemente el padre. Entonces eso es una clara definicion de que tiene que ser una funcion abstracta (`public abstract atacar(): void;`), por lo tanto la clase padre tambien pasa a ser abstracta!

2024-10-24 00:17 UTC, Fran34Arci commented on juegorpg/personaje.ts
> +}
joya ahí quedo entendido...

2024-10-24 00:33 UTC, Fran34Arci commented on juegorpg/main.ts
> +}
mas que confusa, es muy subjetiva y no hacia hincapié en una clase nueva... yo lo plantie como un objeto en este caso arquero que al subir de nivel va desbloqueando sus atributos y funciones. Pero por lo que me planteas este objeto Arquero se debe transformar o pasar a ser Arquero Mejorado... mi pregunta durante la ejecución en el main el objeto creado Arquero1 puede pasar a ser ArqueroMejorado1? .o debo crear un objeto ArqueroMejorado1 directamente que vaya adquiriendo mediante la experiencia los atributos y funciones de la clase Arquero1 hasta llegar a desbloquear las funciones y atributos de la clase ArqueroMejorado1?

2024-10-24 00:47 UTC, SofiZ2001 commented on juegorpg/main.ts
> +}
No esta mal lo que planteas igual Fran, hay muchas formas de encararlo!
Una forma, o la idea del ejercicio es mas simple, es crear una nueva clase de cualquier personaje que tengas que sea como una evolucion de la misma. Como para tener un ejemplo de herencia donde se involucra el padre, el hijo y a su vez el hijo de este.

2024-10-31 11:54 UTC, SofiZ2001 requested changes
Mas comments fran, te sigue quedando pendientre ademas el de la funcion `atacar()` de Personaje que quedó vacío.

2024-10-31 11:54 UTC, SofiZ2001 commented on juegorpg/arqueroEvo.ts
> +Object.assign(this,arquero);
Qué hace esta linea?

2024-10-31 11:54 UTC, SofiZ2001 commented on juegorpg/arqueroEvo.ts
> +    private arquero:Arquero;
Un ArqueroEvolucionado tiene que tener un arquero? Revisar herencia vs composicion

2024-10-31 11:54 UTC, SofiZ2001 commented on juegorpg/arqueroEvo.ts
> +public ataqueFlechasRubi(this,arquero) {
que son this y arquero? No tienen tipos, no se entiende para que son estos parametros

2024-10-31 22:20 UTC, Fran34Arci commented on juegorpg/arqueroEvo.ts
> +Object.assign(this,arquero);
lo de atacar vacío lo tenia acomodado en otra copia ahí lo acomode.
El constructor por parámetro le asigno un objeto, y la linea Object.assign(this, arquero).
copia las propiedades del objeto en este caso arquero al objeto arqueroEvolucion.
El this va separado por una coma por que el Object.assign() es un método que acepta múltiples argumentos,
Object.assign(destino, fuente1,fuente2,fuenteN); ... en este caso destino es el objeto que recibirá las propiedades copiadas. y fuente 1, fuente 2, fuente N son los objetos que contienen las propiedades a copiar.
Object.assign(this, arquero). en este caso el this es el objeto destino y arquero el objeto fuente la coma separan los argumentos que se pasan al método.
así lo encontré

2024-10-31 22:20 UTC, Fran34Arci commented on juegorpg/arqueroEvo.ts
> +    private arquero:Arquero;
Ahí busque, pensé  que necesitaba declarar la variable para utilizarlo dentro de la clase ahí la saque

2024-10-31 22:22 UTC, Fran34Arci commented on juegorpg/arqueroEvo.ts
> +public ataqueFlechasRubi(this,arquero) {
hacen referencia a la clase arquero y sus variables, si no lo paso por parámetro en las funciones, de esa forma no me deja utilizar las funciones con las variables de arquero y tendría que hacer al arqueroevolucionado con nuevas variables de cero

2024-11-01 13:50 UTC, Fran34Arci commented on juegorpg/arqueroEvo.ts
> +public ataqueFlechasRubi(this,arquero) {
esos parámetros me dejaban utilizar sin que me de error en el código las variables de arquero y personaje... pero cuando lo ejecute en su momento no me las modificaba.
ahí acomode la clase y salió andando... y pude entender un poco mas como se maneja la composición

2024-11-01 14:07 UTC, SofiZ2001 requested changes
Otros comments fran

2024-11-01 14:07 UTC, SofiZ2001 commented on juegorpg/arqueroEvo.ts
> +   private arquero: Arquero;
Devuelta, un arquero no debería tener otro arquero! Para que necesitarías esta variable?

2024-11-01 14:07 UTC, SofiZ2001 commented on juegorpg/arqueroEvo.ts
> +class ArqueroEvolucion{
Revisar si este ArqueroEvolucion podría heredar de alguna clase...

2024-11-01 14:07 UTC, SofiZ2001 commented on juegorpg/hechicero.ts
> +    }
Para una mejor lectura, formateate el codigo (Win + Shift + F)

2024-11-01 14:07 UTC, SofiZ2001 commented on juegorpg/personaje.ts
> +
Eliminar espacios en blanco

2024-11-01 14:07 UTC, SofiZ2001 commented on juegorpg/personaje.ts
> +}
Para una mejor lectura, formateate el codigo (Win + Shift + F)

2024-11-01 14:07 UTC, SofiZ2001 commented on juegorpg/guerrero.ts
> +}
Para una mejor lectura, formateate el codigo (Win + Shift + F)

2024-11-01 14:07 UTC, SofiZ2001 commented on juegorpg/arquero.ts
> +}
Para una mejor lectura, formateate el codigo (Win + Shift + F)

2024-11-01 17:07 UTC, Fran34Arci commented on juegorpg/arqueroEvo.ts
> +   private arquero: Arquero;
si saco esa variable me tira error. Y esta haciendo referencia al objeto arquero que quiero pasar por parámetro en el constructor, y de esa variable puedo referenciar el objeto marcado en las funciones de arqueroEvolucionado.

2024-11-01 17:07 UTC, Fran34Arci commented on juegorpg/arqueroEvo.ts
> +class ArqueroEvolucion{
como poder podría heredar de arquero directamente, pero mi idea es usar composición para no hacer herencia de herencia y variar un poco, por eso me estoy quemando los pelos... =)

2024-11-05 12:01 UTC, SofiZ2001 requested changes
2 comments mas fran

2024-11-05 12:01 UTC, SofiZ2001 commented on juegorpg/arqueroEvo.ts
> +    static evolucionar(arquero) {
por que evolucionar es una funcion estatica?
por favor los argumentos de las funciones tienen que ser TIPADOS.

2024-11-05 12:01 UTC, SofiZ2001 commented on juegorpg/arqueroEvo.ts
> +
Pensemos en momento de ejecucion:
Me creo un arqueroEvolucionado, se va a llamar arqueroEvo1.
cuando yo llamo `arqueroEvo1.evolucionar(...)` crea OTRO arquero más. Un arquero no debería crear otro arquero, no tiene sentido

Igualmente el ejercicio no pide una funcionalidad evolucionar, solo la clase en si!

2024-11-15 13:29 UTC, SofiZ2001 requested changes
algunos commennts fran

2024-11-15 13:29 UTC, SofiZ2001 commented on juegorpg/arqueroEvo.ts
> +class ArqueroEvolucion {
ArqueroEvolucion tiene que extender de Arquero

2024-11-15 13:29 UTC, SofiZ2001 commented on juegorpg/arqueroEvo.ts
> +    private arquero: Arquero;
No deberias tener un arquero sino extender del mismo para obtener los atributos. Herencia vs composicion

2024-11-15 13:29 UTC, SofiZ2001 commented on juegorpg/arqueroEvo.ts
> +        if (this.arquero.getNivel() == 4) {
Una vez hecha la herencia simplemente sería` super.getNivel()`. Replicar en los demas lados donde haces `arquero.atributo`

2024-11-15 13:29 UTC, SofiZ2001 commented on juegorpg/arquero.ts
> +    }
Si son funciones que solamente las tiene el arquero evolucion, deben ir en la clase ArqueroEvolucion

2024-11-15 17:41 UTC, Fran34Arci commented on juegorpg/arquero.ts
> +    }
Listo, ahí lo acomode lo que me dijiste y bueno no insisto mas en que evolucione el arquero tiene la clases para hacerlo y listo.

2024-11-15 20:53 UTC, SofiZ2001 approved these changes
lg2m

2024-11-15 22:20 UTC, merged